- name: Simular falha após pausa longa antes do facts no IOS XR
  hosts: all
  gather_facts: no

  tasks:
    - name: Abrir a conexão SSH persistente com o device
      cisco.iosxr.iosxr_command:
        commands:
          - show version

    - name: Esperar mais de 4 minutos
      ansible.builtin.pause:
        minutes: 5

    - name: Coletar facts do IOS XR
      cisco.iosxr.iosxr_facts:
      register: iosxr_facts_out

    - name: Exibir facts coletados
      ansible.builtin.debug:
        var: iosxr_facts_out
