- name: Consultar tags de imagem no Private Automation Hub
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Obter token Bearer
      uri:
        url: "https://172.29.249.135/api/galaxy/v3/auth/token/"
        #url: "https://172.29.249.112/token?"
        method: POST
        user: admin
        password: "redhat"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
        validate_certs: false
      register: token_response

    - name: ah lista de ees
      uri:
        url: "https://172.29.249.112/v2/_catalog"
        method: GET
        return_content: yes
        status_code: 200
        validate_certs: no  # Use 'yes' se o certificado for válido
      register: resultado_a

    - name: ah tags do ee
      uri:
        url: "https://172.29.249.112/v2/de-minimal-rhel8/tags/list"
        method: GET
        headers:
          Authorization: "Bearer {{ token_response.json.token }}"
        return_content: yes
        status_code: 200
        validate_certs: no  # Use 'yes' se o certificado for válido
      register: resultado_a

    - name: Ensure the image does not exist
      infra.ah_configuration.ah_ee_image:
        name: 172.29.249.135/de-minimal-rhel8:0.2
        state: absent
        ah_host: 172.29.249.112
        ah_username: admin
        ah_password: redhat
      ignore_errors: true

- name: Consultar tags de uma imagem no Pulp
  hosts: localhost
  gather_facts: no
  vars:
    pulp_url: "https://172.29.249.112"
    repo_version_href: "/pulp/api/v3/repositories/container/container/ee-minimal-rhel8/versions/"
    username: "admin"
    password: "redhat"
  tasks:
    - name: repository_versions/
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/repository_versions/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false


    - name: repositories/container/container-push/
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/repositories/container/container-push/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      ignore_errors: true

    - name: repository versions
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/repositories/container/container-push/0197131f-001b-7092-8a15-6b6c627dfd3f/versions/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      ignore_errors: true


    - name: version tags
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/content/container/tags/?repository_version=/api/galaxy/pulp/api/v3/repositories/container/container-push/0197131f-001b-7092-8a15-6b6c627dfd3f/versions/7/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      ignore_errors: true

    - name: distributions
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/distributions/container/container/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      ignore_errors: true

    - name: Patch a distribution to point to a specific repository version
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/distributions/container/container/0197131f-01b9-722f-acbc-571fc9ba6a3f/"
        method: PATCH
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
        body_format: json
        body:
          repository: null
          repository_version: "/api/galaxy/pulp/api/v3/repositories/container/container-push/0197131f-001b-7092-8a15-6b6c627dfd3f/versions/7/"
      ignore_errors: true

      #repository was: /api/galaxy/pulp/api/v3/repositories/container/container-push/0197131f-001b-7092-8a15-6b6c627dfd3f/


    - name: distribution for container
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/distributions/container/container/0197131f-01b9-722f-acbc-571fc9ba6a3f/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      ignore_errors: true
    
    - name: delete version
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/repositories/container/container-push/0197131f-001b-7092-8a15-6b6c627dfd3f/versions/1/"
        method: DELETE
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      ignore_errors: true
    


   

   

