- name: Consultar tags de imagem no Private Automation Hub
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Obter token Bearer
      uri:
        url: "https://172.29.249.112/token?service=172.29.249.112&scope=repository:ee-minimal-rhel8:pull"
        method: GET
        user: admin
        password: "redhat"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
        validate_certs: false
      register: token_response

    - name: Obter lista de tags da imagem
      uri:
        url: "https://172.29.249.112/v2/ee-minimal-rhel8/tags/list"
        method: GET
        headers:
          Authorization: "Bearer {{ token_response.json.token }}"
        return_content: yes
        status_code: 200
        validate_certs: no  # Use 'yes' se o certificado for válido
      register: resultado_a

    - name: Exibir tags disponíveis
      debug:
        msg: "{{ resultado_a.json.tags }}"

    - name: Ensure the image does not exist
      infra.ah_configuration.ah_ee_image:
        name: 172.29.249.135/de-minimal-rhel8:0.2
        state: absent
        ah_host: 172.29.249.112
        ah_username: admin
        ah_password: redhat
      ignore_errors: true

    - name: Obter lista de tags da imagem
      uri:
        url: "https://172.29.249.112/v2/ee-minimal-rhel8/tags/list"
        method: GET
        headers:
          Authorization: "Bearer {{ token_response.json.token }}"
        return_content: yes
        status_code: 200
        validate_certs: no  # Use 'yes' se o certificado for válido
      register: resultado_b

    - name: Exibir tags disponíveis
      debug:
        msg: "{{ resultado_b.json.tags }}"


- name: Consultar tags de uma imagem no Pulp
  hosts: localhost
  gather_facts: no
  vars:
    pulp_url: "https://172.29.249.112"
    repo_version_href: "/pulp/api/v3/repositories/container/container/ee-minimal-rhel8/versions/"
    username: "admin"
    password: "redhat"
  tasks:
    - name: content/container/tags/
      uri:
        url: "{{ pulp_url }}/pulp/api/v3/content/container/tags/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      register: resultado_tagsa
      
    - name: content/container/container/
      uri:
        url: "{{ pulp_url }}/pulp/api/v3/distributions/container/container/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      register: resultado_tagsb

    - name: repositories/container/container-push/
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/repositories/container/container-push/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      register: resultado_tagsc


    - name: repositories/container/container-push/versions
      uri:
        url: "{{ pulp_url }}/api/galaxy/pulp/api/v3/repositories/container/container-push/0197131f-001b-7092-8a15-6b6c627dfd3f/versions/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      register: resultado_tagsc

    - name: tag list by version
      uri:
        url: "{{ pulp_url }}api/galaxy/pulp/api/v3/container/tags/?repository_version=/api/galaxy/pulp/api/v3/repositories/container/container-push/0197131f-001b-7092-8a15-6b6c627dfd3f/versions/7/"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: false
      register: resultado_tagsb

   

   

