- name: Listen for events on a webhook
  hosts: localhost
  match_multiple_rules: true
  sources:
   # - name: Source event stream
   #   ansible.eda.event_stream:
   #     name: Splunk

     - name: default webhook
       eda.builtin.webhook:
         host: 0.0.0.0
         port: 5000
         endpoint: double-action-test
  rules:

  - name: Show full webhook event
    condition: event.payload is defined
    actions:
      - print_event:
          pretty: true
      - debug:
          var: event
      - debug:
          var: event.payload

  - name: Type conversion
    condition: event.payload.severity is defined
    actions:
      - set_fact:
          fact:
            severity_int: "{{event.payload.severity | int}}"
            win_host: "{{ event.payload.win_host }}"
            service_name: "{{ event.payload.service_name }}"
      - debug:
          msg: "Severity is {{ severity_int | int  }}"

#  - name: Only debug
#    condition: fact.severity_int is defined
#    actions:
#      - debug:
#          msg: "{{    }}"

  - name: Restart service on host
    condition: fact.severity_int > 4
    action:
      run_job_template:
        name: "Demo Job Template"
        organization: "Default"
       # job_args:
       #   extra_vars:
       #     ansible_window_hosts: "{{ win_host }}"
       #     generic_service_name: "{{ service_name }}"
